---
title: 'Husbands and Wives'
output: html_document
bookToc: true
bookCollapseSection: true
menu:
  after:
    name:
    weight: 1
---

```{r, echo = FALSE, warning = FALSE, message = FALSE}
library(tidyverse) 
library(readxl)
library(plotly)
library(scales)
library(RColorBrewer)
contracts <- read_excel("/Users/professorserrano/Desktop/Documents/Video Essays/Law/contracts_gender_r_2.xlsx")
defs <- read_excel("/Users/professorserrano/Desktop/Documents/Video Essays/Law/defs_r.xlsx")
plfs <- read_excel("/Users/professorserrano/Desktop/Documents/Video Essays/Law/plfs_r.xlsx")
parties <- read_excel("/Users/professorserrano/Desktop/Documents/Video Essays/Law/parties_r.xlsx")
cites <- read_excel("/Users/professorserrano/Desktop/Documents/Video Essays/Law/cites_for_contracts.xlsx")
gendertotaltable <- read_excel("/Users/professorserrano/Desktop/Documents/Video Essays/Law/gendertotaltable.xlsx")
partnertable <- read_excel("/Users/professorserrano/Desktop/Documents/Video Essays/Law/partner_table.xlsx")

names(gendertotaltable)[1] <- "gender"
names(gendertotaltable)[5] <- "percentage"
opts <- options(knitr.kable.NA = "")

parties <- parties %>%
  full_join(cites)
names(parties)[4] <- "name"
contracts <- contracts %>%
  mutate(simplecite = cite) %>%
  mutate(simplecite = str_extract(simplecite, "[^,]+"))

names(parties)[9] <- "cite"

n_parties_joiner <- parties %>%
  group_by(cite) %>%
  count() %>%
  mutate(n_parties = n) %>%
  select(cite, n_parties)

parties <- parties %>%
  mutate(simplecite = cite) %>%
  mutate(simplecite = str_extract(simplecite, "[^,]+"))

contracts <- contracts %>%
  full_join(n_parties_joiner)

```


## Marriage and Family 

This was by far the variable that stood out most to me while going through the book. 57% of the women in the casebook appear with (or regarding) a spouse or partner, as opposed to 19% of men. 13% of women are described regarding some other familiar relationship (aunt, sister, mother, etc.) as opposed to 10% of men. In all, nearly 3 of every 4 women are described by their familiar relations as opposed to less than a third of men.  

Most of these are members of one of the 24 couples who appeared with or against a heterosexual partner in a relationship. 

Two men and two women had their relationships described with reference to the proceedings but without their partner appearing. I.G. Katz brought a promissory estoppel claim against a company the president of which “was also the brother of Katz’s wife,” establishing the connection between Katz and the company; moreover, his wife would benefit from a Social Security clause in the promised contract. Russell N. Pelo was involuntarily committed to a hospital after he telephoned his wife to make threats of self harm, relevant to the context of his refusal to pay. Sondra Locke’s dispute with Warner Bros. is framed as something patronizingly set up for her by her ex Clint Eastwood (not a party), relevant to the argument about good faith. Coretta Scott King brings her case on behalf of her family estate, and is actually a great example of rhetoric relating a woman to a husband but still giving her full agency: “the plaintiff, Coretta Scott King, in her capacity as administratix of the estate of her late husband, and in her individual capacity, appeals...” 237

One man and one woman had their marital status described as a strange, but seemingly purposeful, aside. Dohrmann v. Swaney: “Dohrmann was a 40-year-old neurosurgeon, married to Dr. Helen Dohrmann” 130, where his and his wifes’ professional status establish a class level in this case about fraud? In Aceves v. U.S. Bank, N.A. the judge present the plaintiff, a woman independently bringing a suit whose spouse appears only as a minor detail in the rest of the opinion, as “Claudia Aceves, a married woman.” (255) The case is about bankruptcy – perhaps her marriage establishes some kind of moral credibility? 

