---
title: "On Style"
bookToc: true
output: html_document
menu:
  after:
    name:
    weight: 1
---

## "Frugging KCP" and the word "Fruggish" are intentionally irreverent, and I think she wouldn't mind. 

The following is from a section titled "On Style" in Frug's last work, "A Postmodern Feminist Legal Manifesto (An Unfinished Draft)."

#### *The medium is the message*
> *Style is important in postmodern work. The medium* is *the message, in some cases ... when style is salient, it is characterized by irony and by wordplay that is often dazzlingly funny, smart, and irreverent. Things aren't just what they seem.*

## Adjectivization

In a project that I co-authored (pending publication, so I'll be light on details) we reviewed a large sample of academic book reviews. Over 90 mens' names were somehow "adjectivized" within the reviews - Foucauldian, Wittgensteinian, Hegelian - or "nouned" - Marxism, Darwinism - as opposed to only three women. This coincided with a qualitative pattern of men writing *very* favorably about other men, to fairly sycophantic extremes. 

The outcome we proposed in that paper is not that more women get sycophantic praise in book reviews, but to tone the personal veneration down in general. It can be dangerous to elevate scholars to lofty, elite status. 

#### *Irony*
> *Irony, for example, is a stylistic method of acknowledging and challenging a dominant meaning, of saying something and simultaneously denying it.*


## It Sounds Funny 

So the choice of adjectivizing with "Fruggish" and verb-ifying with "Frugging" adopts this largely masculine technique - a sort of grammatical veneration, recognizing the greatness of *a man* and *his* ideas. I think Frug and Frug's ideas do deserve acknowledgment, study, replication, and respect. But part of postmodernism is questioning power and stopping short of veneration. So I acknowledge the dominant meaning of adjectivization, centering Frug grammatically because this project is so heavily inspired by her. At the same time, I challenge its connotation with humor (idk about dazzlingly funny but i try). 
